# Declaration of Doctrine on Sexuality {#sec-declaration-of-doctrine-on-sexuality}

## Introduction

Since the mid-twentieth century, rebellion against God’s divine pattern of sex within the loving union of lifelong, monogamous, heterosexual marriage has become widespread, and attacks against that pattern are increasingly perpetrated in concert with the civil magistrate. Thus for the protection of the Christian church’s conscience and the purity of the faith once for all delivered to the saints, it has become necessary for Christians to declare our scriptural convictions and commitments concerning sexuality and marriage. These convictions and commitments are testified to by God’s natural revelation and they are explicitly commanded by God’s special revelation in Holy Scripture. Prior generations of Christians and non-Christians alike lived under the beneficial constraints of laws written to protect civil society from sexual relations outside the commands of Scripture. Western law in particular reinforced God’s law concerning sexual relations and His Creation Order of Adam first, then Eve. For this reason, the church had little need to adopt doctrinal creeds or statements concerning sexuality. Now though, with the heathens’ attack growing ever more intense and becoming institutionalized by the power of civil authority, the time has come for the church to declare her allegiance to God’s law of male and female, and to do so specifically, forthrightly, and with confidence in the wisdom and kindness of God. To that end, we declare our biblical convictions and commitments for the glory of Christ and the good of His church.

## On the Order of Creation

1. []{#dds-01}“In the day when God created man, He made him in the likeness of God. God created them male and female, and He blessed them and named them Man in the day when they were created.”[^1] God formed the first male, Adam, from the dust of the ground.[^2] He made the first female, Eve, from Adam’s rib and presented her to Adam to be a helper perfectly suited to him.[^3] Adam called his wife “Woman, because she was taken out of Man.”[^4] God named the human race, consisting of both males and females, “Man” after the first man Adam, whose name is simply the Hebrew word for “man” used throughout the Old Testament.

2. []{#dds-02}From the beginning, God gave Adam authority over Eve and responsibility for her. This authority and responsibility are inseparably joined together, and they lay the foundation for God’s decree of father-rule (patriarchy) throughout Scripture. Eve was created for Adam’s sake[^5] to be a “help meet” for him, that is, a fitting helper.[^6] Man is to love and take responsibility for woman by leading her and laying down his life for her, providing a living illustration of Christ’s sacrificial leadership of His Bride, the church.[^7]

3. []{#dds-03}God’s Creation Order of man and woman was established while man was in a state of innocence before the Fall and is therefore a universal rule for all mankind. God’s creation of Adam first, then Eve, is the origin of Scripture’s condemnation of woman exercising authority over man[^8] and is further elucidated by Scripture’s declaration that man is the glory of God, but woman is the glory of man.[^9] This Creation Order is also the source of Scripture’s commands that husbands love their wives as their own bodies,[^10] and that wives be subject to their husbands in everything.[^11]

4. []{#dds-04}God’s subordination of woman to man in no way diminishes woman’s perfect equality with man in essence, worth, and honor.[^12]

## On Sexual Identity

5. []{#dds-05}God’s bifurcation of mankind into two and only two sexes, male and female, is an act of His creative will and power and continues through all generations since Adam, our first father.

6. []{#dds-06}God forms each person in his mother’s womb and creates each unborn child as either male or female.[^13] From the moment of conception,[^14] males are distinct from females, and females are distinct from males.[^15] What God has decreed as each one’s sex at the moment of conception, either male or female, is His gift and must be received with gratitude, each man living out his manhood and each woman her womanhood, in humble reliance upon God’s grace.[^16]

7. []{#dds-07}The proper conception of “sexual identity” is a matter of living in accordance with the genetic sex given to us by God, either male or female. Genetic sex and sexual identity cannot be separated, and they remain bound together throughout one’s life. Sexuality does not admit of gradations. You are either male or female, not part male and part female. Nor are there a great multitude of sexual identities. There are only two, male and female.

8. []{#dds-08}Any attempt of a man to play the woman or a woman to play the man violates God’s decree, attacks His created order, and constitutes sin so serious that God Himself pronounces it an “abomination.”[^17]

   a. This sin includes transvestism and any efforts, including chemical or surgical, as well as behavioral (e.g., effeminacy[^18]), to reject and efface one’s sex and to adopt characteristics of the opposite sex.  
   b. This sin also includes the conscription of woman as a military combatant or the placing of woman in harm’s way as a law enforcement officer. As life-giver,[^19] woman has always been honored by man’s defense of her and her children. Furthermore, Christ Jesus gave up His life for His Bride, the church, and man is to follow Christ’s example by laying down his life in defense of woman.[^20] A civil magistrate defaces woman’s sexuality by placing her in the uniform of a combatant[^21] and commanding her to take up arms. Further, given woman’s comparative physical weakness in the face of male enemies, such magistrates place their homeland at unnecessary risk.[^22] Finally, female military combatants of childbearing age often (whether knowingly or unknowingly) place at risk unborn children, which is an act contrary to the just war principle of avoiding needless loss of life.

## On Marriage

9. []{#dds-09}Marriage is instituted by God as the lifelong[^23] monogamous[^24] union of one male and one female.[^25] This relationship, with these limitations, was established while man was in a state of innocence before the Fall,[^26] and its pattern is established for all members of the human race. Marriage is an honorable estate that God Himself made, and it symbolizes to us the mystical union which is between Christ and His church.[^27]

10. []{#dds-10}Just as Adam was given authority over Eve and responsibility for her, and just as Christ is the head of the church, so each husband is the head of his wife.[^28] God commands each husband to love his wife, “just as Christ also loved the church and gave Himself up for her.”[^29]

11. []{#dds-11}Just as Eve was created for Adam, and just as the church is subject to Christ, so each wife is to be subject to her own husband in everything.[^30]

12. []{#dds-12}For centuries, Christians have recognized the following vital purposes of marriage:  
“Marriage was ordained for the mutual help of husband and wife, for the increase of mankind with a legitimate issue, and of the Church with an holy seed; and for preventing of uncleanness.”[^31]

13. []{#dds-13}When sin entered the human race, marriage was severely harmed.[^32] Wives began rebelling against their husbands’ authority, husbands began abdicating and abusing their authority over their wives, and sexual immorality began to corrupt marital intimacy, all of which dishonor God and bring shame to the name of Christ and His Bride, the church. God therefore created laws to govern the violation of His established pattern, while not changing the pattern.[^33] Since marriage is a lifelong and monogamous union, God forbids divorce except in two circumstances: (1)\ when one spouse abandons the other,[^34] and (2)\ when a spouse engages in sexual immorality.[^35]

14. []{#dds-14}God in His Law forbids any deviation from the established pattern of marriage and from His gift of sexual union to be enjoyed by a married couple. These forbidden deviations include lust (i.e., sexual desire for anyone but one’s spouse), pornography,[^36] masturbation (including simulated copulation with any inanimate object, no matter how lifelike),[^37] fornication,[^38] adultery,[^39] polygamy,[^40] incest,[^41] pedophilia,[^42] homosexuality,[^43] and bestiality.[^44] Because the heart of man is deceitful above all things and desperately wicked,[^45] it is impossible to catalog fully all forms of sexual immorality and degradation.

15. []{#dds-15}Presently, there is widespread disregard, even scorn, for the divine standard of sexuality and marriage as revealed in Scripture. This disregard, which is found both in the world and in many churches, endangers the family (our basic social unit) and causes much suffering to the innocent, especially children. When found in the church, it brings shame to the name of Christ.[^46]

## On Faith and Repentance

16. []{#dds-16}God offers the free gift of forgiveness for all sinful corruptions of sexuality through repentance and faith in Jesus. As the household of faith, the church’s duty and privilege is to proclaim this repentance and forgiveness. The church is also to seek the healing of those harmed by these sins and to assist parents in training boys to be men and girls to be women.[^47]

17. []{#dds-17}The church has sinned and failed in many ways to obey God’s commands of sexuality, even teaching many sexual sins and errors as though they were virtues and truths. This unfaithfulness and the fact that sinners on the road of repentance and faith in Jesus Christ often enter the church bound in deep patterns of sexual sin mean that repentance for sexual sinners may be a gradual and complicated process. Because of this, wise and compassionate pastoral discretion is necessary to practically apply the Bible’s teaching on sexuality.

## Afterword

This Declaration does not exhaust the extent of our beliefs and practices. The Bible itself, as the inspired and infallible Word of God that speaks with final authority concerning truth, morality, and the proper conduct of mankind, is the sole and final source of authority for all that we believe and do. For purposes of Evangel Presbytery’s faith, doctrine, practice, policy, and discipline, the membership of the Presbytery (as constituted under [BCO 15.1](https://bco.evangelpresbytery.com/02-Form-of-Government.html#anchor-15-1)) is the Presbytery’s final interpretive authority on the Bible’s meaning and application, including for any purpose under [BCO 15.8](https://bco.evangelpresbytery.com/02-Form-of-Government.html#anchor-15-8). As the practical outworking of the beliefs set forth in this Declaration, Evangel Presbytery has adopted policies relating to marriage and sexuality in [BCO 71](https://bco.evangelpresbytery.com/02-Form-of-Government.html#anchor-71) and [BCO 72](https://bco.evangelpresbytery.com/02-Form-of-Government.html#anchor-72).

---

## Notes

[^1]: Genesis 5:2. Unless otherwise indicated, all Scripture references are to the New American Standard Bible (1995).  

[^2]: See Genesis 2:7.  

[^3]: See Genesis 2:20–22. See also 1\ Corinthians 11:11–12: “However, in the Lord, neither is woman independent of man, nor is man independent of woman. For as the woman originates from the man, so also the man has his birth through the woman; and all things originate from God.”  

[^4]: Genesis 2:23.  

[^5]: “For man does not originate from woman, but woman from man; for indeed man was not created for the woman’s sake, but woman for the man’s sake.” 1\ Corinthians 11:8–9.  

[^6]: “And the LORD God said, It is not good that the man should be alone; I will make him an help meet for him.” Genesis 2:18 (KJV).  

[^7]: See Ephesians 5:25–33.  

[^8]: “But I do not allow a woman to teach or exercise authority over a man, but to remain quiet. For it was Adam who was first created, and then Eve. And it was not Adam who was deceived, but the woman being deceived, fell into transgression.” 1\ Timothy 2:12–14.  

[^9]: “For a man ought not to have his head covered, since he is the image and glory of God; but the woman is the glory of man.” 1\ Corinthians 11:7.  

[^10]: See Ephesians 5:25, 28; cf. Colossians 3:19.  

[^11]: See Ephesians 5:22, 24; cf. Colossians 3:18 and Titus 2:5.  

[^12]: “God created man in His own image, in the image of God He created him; male and female He created them.” Genesis 1:27. See also 1\ Peter 3:7: “…you wives, be submissive to your own husbands. … You husbands in the same way, live with your wives in an understanding way, as with someone weaker, since she is a woman; and show her honor as a fellow heir of the grace of life, so that your prayers will not be hindered.”  

[^13]: See Psalm 139:13–16; Genesis 5:2.  

[^14]: Because all truth is God’s truth and God is not a man that He should lie (Numbers 23:19), what God reveals through His creation never contradicts what He reveals in His Word. Thus, genetics and other scientific disciplines, when not abused or corrupted for sinful purposes, can declare truth. It is proper then to recognize that a man conceived and born a man is genetically male, and a woman conceived and born a woman is genetically female.  

[^15]: This is not to address the extremely rare case of intersex children born with a variety of conditions, including: Not XX and Not XY, Hypospadias, Androgen Insensitivity Syndrome, Ovotestes, etc. “Intersex” is a medical diagnosis of atypical male or female anatomies not to be confused with those born with typical male or female anatomies who claim a “transgender” or “transsexual” identity. The suffering of those born with physical anomalies must not be used to justify the rebellion of those who repudiate the sex God made them. All such abnormalities and genetic deformities along with illness of any kind, pain, suffering, and death itself, are a result of the Fall as described in Genesis 3, and pass through God’s sovereign hand as He gives to each man both good and adversity. See Exodus 4:11; Job 2:9–10; John 9:1–7.  

[^16]: “Only, as the Lord has assigned to each one, as God has called each, in this manner let him walk.” 1\ Corinthians 7:17.  

[^17]: “A woman shall not wear man’s clothing, nor shall a man put on a woman’s clothing; for whoever does these things is an abomination to the LORD your God.” Deuteronomy 22:5. See also 1\ Corinthians 6:9–10: “Or do you not know that the unrighteous will not inherit the kingdom of God? Do not be deceived; neither fornicators, nor idolaters, nor adulterers, nor effeminate, nor homosexuals, nor thieves, nor the covetous, nor drunkards, nor revilers, nor swindlers, will inherit the kingdom of God.”  

[^18]: See 1\ Corinthians 6:9–10.  

[^19]: See Genesis 3:20.  

[^20]: See Ephesians 5:25.  

[^21]: See Deuteronomy 22:5. In the text, “man’s clothing”—or, in the KJV, “that which pertaineth to a man”—refers to the clothing and weapons worn by men for combat.  

[^22]: See 1\ Peter 3:7 on the comparative weakness of women. Jeremiah 50:37 and Nahum 3:13 both make references to men “becoming women” as descriptive of their vulnerability to attack.  

[^23]: “So then, if while her husband is living she is joined to another man, she shall be called an adulteress; but if her husband dies, she is free from the law, so that she is not an adulteress though she is joined to another man.” Romans 7:3.  

[^24]: “You shall not commit adultery.” Exodus 20:14. See also 1\ Timothy 3:2: “An overseer, then, must be above reproach, the husband of one wife.”  

[^25]: “But from the beginning of creation, God MADE THEM MALE AND FEMALE. FOR THIS REASON A MAN SHALL LEAVE HIS FATHER AND MOTHER, AND THE TWO SHALL BECOME ONE FLESH; so they are no longer two, but one flesh. What therefore God has joined together, let no man separate.” Mark 10:6–9. See also 1\ Corinthians 6:9–10.  

[^26]: See Genesis 2:18–24.  

[^27]: “Husbands, love your wives, just as Christ also loved the church and gave Himself up for her, so that He might sanctify her, having cleansed her by the washing of water with the word, that He might present to Himself the church in all her glory, having no spot or wrinkle or any such thing; but that she would be holy and blameless. So husbands ought also to love their own wives as their own bodies. He who loves his own wife loves himself; for no one ever hated his own flesh, but nourishes and cherishes it, just as Christ also does the church, because we are members of His body. FOR THIS REASON A MAN SHALL LEAVE HIS FATHER AND MOTHER AND SHALL BE JOINED TO HIS WIFE, AND THE TWO SHALL BECOME ONE FLESH. This mystery is great; but I am speaking with reference to Christ and the church.” Ephesians 5:25–32.  

[^28]: “For the husband is the head of the wife, as Christ also is the head of the church, He Himself being the Savior of the body.” Ephesians 5:23.  

[^29]: Ephesians 5:25.  

[^30]: “Wives, be subject to your own husbands, as to the Lord. For the husband is the head of the wife, as Christ also is the head of the church, He Himself being the Savior of the body. But as the church is subject to Christ, so also the wives ought to be to their husbands in everything.” Ephesians 5:22–24.  

[^31]: Westminster Confession of Faith, ch. 24 (“Of Marriage and Divorce”), para. 2. Westminster Confession of Faith hereinafter abbreviated as “WCF.”  

[^32]: “When the woman saw that the tree was good for food, and that it was a delight to the eyes, and that the tree was desirable to make one wise, she took from its fruit and ate; and she gave also to her husband with her, and he ate. Then the eyes of both of them were opened, and they knew that they were naked; and they sewed fig leaves together and made themselves loin coverings. They heard the sound of the LORD God walking in the garden in the cool of the day, and the man and his wife hid themselves from the presence of the LORD God among the trees of the garden. Then the LORD God called to the man, and said to him, ‘Where are you?’ He said, ‘I heard the sound of You in the garden, and I was afraid because I was naked; so I hid myself.’ And He said, ‘Who told you that you were naked? Have you eaten from the tree of which I commanded you not to eat?’ The man said, ‘The woman whom You gave to be with me, she gave me from the tree, and I ate.’” Genesis 3:6–12.  

[^33]: “He said to them, ‘Because of your hardness of heart Moses permitted you to divorce your wives; but from the beginning it has not been this way.’” Matthew 19:8.  
\ \ \ \ “For truly I say to you, until heaven and earth pass away, not the smallest letter or stroke shall pass from the Law until all is accomplished.” Matthew 5:18.  

[^34]: See 1\ Corinthians 7:12–13, 15–16. Abandonment or “wilful desertion” (WCF 24.6) is not limited only to cases of one spouse’s unjustified departure and refusal to be reconciled to the abandoned or injured spouse. A state of willful desertion also exists if the offending party’s conduct is so egregious that the injured party is forced to leave the marital home and reconciliation is impossible due to the nature or seriousness of the sin and the offending party’s persistent impenitence.

[^35]: “It was said, ‘Whoever sends his wife away, let him give her a certificate of divorce’; but I say to you that everyone who divorces his wife, except for the reason of unchastity, makes her commit adultery; and whoever marries a divorced woman commits adultery.” Matthew 5:31–32. See also WCF 24.6.  

[^36]: “But I say to you that everyone who looks at a woman with lust for her has already committed adultery with her in his heart.” Matthew 5:28.  

[^37]: “Finally then, brethren, we request and exhort you in the Lord Jesus, that as you received from us instruction as to how you ought to walk and please God (just as you actually do walk), that you excel still more. For you know what commandments we gave you by the authority of the Lord Jesus. For this is the will of God, your sanctification; that is, that you abstain from sexual immorality; that each of you know how to possess his own vessel in sanctification and honor, not in lustful passion, like the Gentiles who do not know God; and that no man transgress and defraud his brother in the matter because the Lord is the avenger in all these things, just as we also told you before and solemnly warned you. For God has not called us for the purpose of impurity, but in sanctification. So, he who rejects this is not rejecting man but the God who gives His Holy Spirit to you.” 1\ Thessalonians 4:1–8.  
\ \ \ \ “But I say, walk by the Spirit, and you will not carry out the desire of the flesh.” Galatians 5:16.

[^38]: “Marriage is to be held in honor among all, and the marriage bed is to be undefiled; for fornicators and adulterers God will judge.” Hebrews 13:4.  

[^39]: “You shall not commit adultery.” Exodus 20:14.  

[^40]: “And He answered and said, ‘Have you not read that He who created them from the beginning MADE THEM MALE AND FEMALE, and said, “FOR THIS REASON A MAN SHALL LEAVE HIS FATHER AND MOTHER AND BE JOINED TO HIS WIFE, AND THE TWO SHALL BECOME ONE FLESH”? So they are no longer two, but one flesh. What therefore God has joined together, let no man separate.’” Matthew 19:4–6.  
\ \ \ \ “An overseer, then, must be above reproach, the husband of one wife…” 1\ Timothy 3:2.  

[^41]: See Leviticus 20:11–12, 14, 17, 19–21.  

[^42]: “He said to His disciples, ‘It is inevitable that stumbling blocks come, but woe to him through whom they come! It would be better for him if a millstone were hung around his neck and he were thrown into the sea, than that he would cause one of these little ones to stumble.’” Luke 17:1–2.  

[^43]: “You shall not lie with a male as one lies with a female; it is an abomination.” Leviticus 18:22.  

[^44]: “Also you shall not have intercourse with any animal to be defiled with it, nor shall any woman stand before an animal to mate with it; it is a perversion.” Leviticus 18:23.  

[^45]: See Jeremiah 17:9.  

[^46]: “However, because by this deed you have given occasion to the enemies of the LORD to blaspheme, the child also that is born to you shall surely die.” 2\ Samuel 12:14. This text about God’s discipline on King David for his adultery with Bathsheba demonstrates dishonor coming to God’s holy name and suffering coming to the members of a man’s family—both caused by the sin of the father.
“For ‘THE NAME OF GOD IS BLASPHEMED AMONG THE GENTILES BECAUSE OF YOU,’ just as it is written.” Romans 2:24.  

[^47]: “Such were some of you; but you were washed, but you were sanctified, but you were justified in the name of the Lord Jesus Christ and in the Spirit of our God.” 1\ Corinthians 6:11.  
\ \ \ \ “The Spirit of the LORD God is upon me, / Because the LORD has anointed me / To bring good news to the afflicted; / He has sent me to bind up the brokenhearted, / To proclaim liberty to captives / And freedom to prisoners.” Isaiah 61:1.  
\ \ \ \ “A BATTERED REED HE WILL NOT BREAK OFF, AND A SMOLDERING WICK HE WILL NOT PUT OUT, UNTIL HE LEADS JUSTICE TO VICTORY.” Matthew 12:20.  
\ \ \ \ As one example of scriptural instructions given to men as distinct from those given to women, see Titus 2:2ff.: “Older men are to be temperate, dignified, sensible, sound in faith, in love, in perseverance. Older women likewise are to be reverent in their behavior, not malicious gossips nor enslaved to much wine, teaching what is good, so that they may encourage the young women to love their husbands, to love their children, to be sensible, pure, workers at home, kind, being subject to their own husbands, so that the word of God will not be dishonored. Likewise urge the young men to be sensible…”  
