# Declaration of Doctrine on Abortion {-}

## Introduction {-}

When the history of our time is written, it will be a record of bloodshed on a scale previously unimaginable across the history of mankind. This bloodshed began with two World Wars in which combatant fatalities were numbered in the tens of millions. By the end of the Second World War, militaries of both sides had turned to targeting their enemy’s civilians so that combatant fatalities were surpassed by non-combatant fatalities. The growth in bloodshed then turned from soldiers killing soldiers, to soldiers killing civilians, to Communist rulers killing their own citizens. Russia’s Joseph Stalin and China’s Mao Zedong slaughtered well over 100 million of their own people.

But it was not until bloodshed entered the home, and fathers and mothers killed their own offspring, that the bloody count exploded. Five decades into abortion’s slaughter, the death toll now is in the billions, and growing. Unmoored from the restraints of God’s Law, man has devised ever more sophisticated ways to oppress and destroy the weak, aided in this by technology that magnifies his corruption. From the proliferation of contraceptive[^1] (and often abortifacient[^2]) drugs, to the denial of life at the moment of conception, to the mass use of abortifacient drugs (e.g., RU-486), to the manipulation and destruction of human life by reproductive technology (i.e., in-vitro fertilization), and now to sex-selective abortion, the history of the twentieth and twenty-first centuries is of man using his ingenuity to advance his lusts: “Truly, this only I have found: That God made man upright, But they have sought out many schemes” (Eccl. 7:29).

Until the twentieth century, the Church’s condemnation of such wickedness had been united and unanimous. Beginning in the 1930s, historic Protestant denominations began to soften and remove their long-standing opposition to contraception. So when the offensive shifted to its sister fruit, abortion, Protestants no longer had a framework for interpreting (and then opposing) this evil, and denomination after denomination were either supportive or silent. In this context, the bloodshed grew, not only among unbelievers, but among conservative Christians as well.

There were, eventually, also victories. Starting in the early 1980s, Protestants recovered some of their will to fight this evil, and persistent work over fifty years yielded a substantial victory in the Supreme Court’s 2022 *Dobbs* ruling. Yet even the overturning of *Roe v. Wade* is but a partial victory—especially as it has revealed even among conservative Christians the lack of will to end abortion. For even as we, God’s people, have opposed abortion, the blood has continued to stain our country, our streets, even our homes.

Yet God is faithful, and He has promised to purify His Church with the truth. So it is our desire to repent of the Church’s failure in the matter of abortion, and to read with new eyes and new hearts God’s commands concerning life, death, and children. The statements below are not everything we teach (or that must be taught) on these matters, but, like Augustine, we speak even in part so that we may not be entirely silent.
