# Declaration of Doctrine on Abortion {#sec-declaration-of-doctrine-on-abortion}

## Introduction

When the history of our time is written, it will be a record of bloodshed on a scale previously unimaginable across the history of mankind. This bloodshed began with two World Wars in which combatant fatalities were numbered in the tens of millions. By the end of the Second World War, militaries of both sides had turned to targeting their enemy’s civilians so that combatant fatalities were surpassed by non-combatant fatalities. The growth in bloodshed then turned from soldiers killing soldiers, to soldiers killing civilians, to Communist rulers killing their own citizens. Russia’s Joseph Stalin and China’s Mao Zedong slaughtered well over 100 million of their own people.

But it was not until bloodshed entered the home, and fathers and mothers killed their own offspring, that the bloody count exploded. Five decades into abortion’s slaughter, the death toll now is in the billions, and growing. Unmoored from the restraints of God’s Law, man has devised ever more sophisticated ways to oppress and destroy the weak, aided in this by technology that magnifies his corruption. From the proliferation of contraceptive[^1] (and often abortifacient[^2]) drugs, to the denial of life at the moment of conception, to the mass use of abortifacient drugs (e.g., RU-486), to the manipulation and destruction of human life by reproductive technology (i.e., in-vitro fertilization), and now to sex-selective abortion, the history of the twentieth and twenty-first centuries is of man using his ingenuity to advance his lusts: “Truly, this only I have found: That God made man upright, But they have sought out many schemes” (Eccl. 7:29).

Until the twentieth century, the Church’s condemnation of such wickedness had been united and unanimous. Beginning in the 1930s, historic Protestant denominations began to soften and remove their long-standing opposition to contraception. So when the offensive shifted to its sister fruit, abortion, Protestants no longer had a framework for interpreting (and then opposing) this evil, and denomination after denomination were either supportive or silent. In this context, the bloodshed grew, not only among unbelievers, but among conservative Christians as well.

There were, eventually, also victories. Starting in the early 1980s, Protestants recovered some of their will to fight this evil, and persistent work over fifty years yielded a substantial victory in the Supreme Court’s 2022 *Dobbs* ruling. Yet even the overturning of *Roe v. Wade* is but a partial victory—especially as it has revealed even among conservative Christians the lack of will to end abortion. For even as we, God’s people, have opposed abortion, the blood has continued to stain our country, our streets, even our homes.

Yet God is faithful, and He has promised to purify His Church with the truth. So it is our desire to repent of the Church’s failure in the matter of abortion, and to read with new eyes and new hearts God’s commands concerning life, death, and children. The statements below are not everything we teach (or that must be taught) on these matters, but, like Augustine, we speak even in part so that we may not be entirely silent.

## Statements

[]{#anchor-dda-statement-01}1. The Protestant Church’s weakness in anthropology, uncritical embrace of contraception, and tacit acceptance of abortion are scandals, and the products of doctrinal passivity and retreat. From these we must repent, and must recover the biblical and historical doctrines of anthropology to address the evils facing us today.

[]{#anchor-dda-statement-02}2. God created man in His own image—male and female He created them. The life of man on this earth begins at the moment of conception, which is the joining of the father’s sperm with the mother’s egg. From that point onward he bears the image of God, is the pinnacle of God’s Creation, and possesses all the rights of personhood.

[]{#anchor-dda-statement-03}3. Abortion as condemned by Scripture and the Presbytery means the taking of a human life[^3] at any point from conception to birth.[^4] It is a grave sin in the sight of God, and is opposed in both Old and New Testaments, as well as by all branches of the Church throughout all time.[^5] Further, as the murder of an unborn child, abortion is a particularly heinous offense, and Scripture condemns it in the strongest terms.[^6]

[]{#anchor-dda-statement-04}4. Abortion is an offense against reason, society, the laws of nature, the woman’s conscience, and most of all, the Law of God, whose Sixth Commandment forbids murder and commands the protection and preservation of human life.[^7] Man’s law can never repeal, abrogate, or supersede God’s Law, which is perfect.

[]{#anchor-dda-statement-05}5. The taking of a human life is justifiable only in limited circumstances (self-defense, capital punishment, and just war) to protect oneself or another man, woman, or child from the attack of an aggressor. Abortion has no commonality with any of these; it is itself an attack upon the defenseless.

[]{#anchor-dda-statement-06}6. Many forms of birth control operate not only by preventing conception but also by preventing the implantation of a new embryo in the mother’s womb. This is especially true of intrauterine devices and hormonal contraceptive methods, including the birth control pill and the morning-after pill. By denying sustenance to a new life, they cause the death of an unborn child at one of its earliest stages. This is the commission of an unjustifiable homicide.

[]{#anchor-dda-statement-07}7. God created marriage to bring forth life, commanding Adam and Eve in the state of perfection to “be fruitful and multiply.” All creation bears witness to this principle, and, still today, all husbands and wives are to obey this Creation ordinance.[^8] Moreover, throughout history both pagans and Christians have recognized an essential connection between abortion and contraception, and condemnation of the one has gone hand in hand with that of the other. Thus, while we may *distinguish* (non-abortifacient) contraception from abortion, we cannot wholly *separate* the two. The sexual union between man and woman is itself theological revelation about marriage, Christ, and the Church, and the unity of marriage’s procreative and unitive purposes is fundamental to God’s institution of marriage.

[]{#anchor-dda-statement-08}8. Nevertheless, in this fallen world situations arise in which this Creation ordinance collides with other commands of God. By God’s grace, such situations are exceptional and generally temporary; often, they call for wise and sensitive pastoral care. Any decision to frustrate natural conception must be taken recognizing God’s command of fruitfulness as good, not in fearful rejection of it—and with a firm resolve not to use any contraceptive method with the smallest agency of killing the unborn child. In the pattern of our lives, we (and all men) are to show that our marital unions are marked by openness to the children God has designed for us, and by our willingness to nourish them with life.

[]{#anchor-dda-statement-09}9. While science has revealed much wonder in how God fashions us in the womb, Christians must not reduce this mystery to the mechanical and empirical. Only a glimpse of this process lies before our eyes; God alone beholds our frame as we are “made in secret and skillfully wrought in the lowest parts of the earth” (Ps. 139:15). Scientific and medical advancements are the Lord’s gifts to mitigate the sorrows of this world, including infertility, yet Christians must tread with care in all such areas, recognizing the secret things of the Lord (Deut. 29:29). It belongs to God alone to join soul and body, and whatever technological or medical developments promise to heal the pain of infertility must be subjected to careful study before any of them is used. Nor must we ever treat the fruit of the womb as simply a DNA-bearing zygote instead of an immortal bearer of God’s image, or profane the sacred unitive context in which God has designed that life to be nourished.

[]{#anchor-dda-statement-10}10. As but one example of this, in-vitro fertilization as typically practiced[^9] is illicit and immoral. By design, it separates the unitive and procreative functions of marital intercourse, and supplants this unitive act with mechanical and technological production. But even worse, it results in the abuse and death of millions of preborn children. For Christians to foster and subsidize an industry of mechanized reproduction is a scandal. Yes, infertility is a grievous sorrow to bear, and medical assistance should of course be sought to alleviate it. But God’s people seek the Lord, first, knowing He is pleased to give good gifts to His children. And if, despite patience, prayer, and lawful medical intervention, God’s answer is “no,” Christians receive this by faith, rather than by striving to engineer fertility *no matter the cost*. He is the One Who opens and closes the womb, and by His design our children are conceived in the secret places. Finally, let it be said clearly that “You shall not murder” is true and binding even if murdering provides a couple with a child of their own.

[]{#anchor-dda-statement-11}11. Rape and incest, while serious sins of their own, do not justify abortion. Rather, abortion in these circumstances magnifies and perpetuates violence by inflicting it on the innocent unborn child, punishing him for the crime of another.[^10]

[]{#anchor-dda-statement-12}12. Christians should not be misled by specious arguments for abortion on the basis of “the health of the mother,” which involve not a genuine ethical dilemma, but a category so broad as to regard any physical or psychological impediment as grounds for the murder of a child.[^11]

[]{#anchor-dda-statement-13}13. Many of us among the people of God have killed our children by abortion. The women and men guilty of this sin should be exhorted by their pastors to faith and repentance that neither disregards their moral agency nor removes their hope in the grace of God. Freedom from the bloodguilt of abortion comes not by claiming victimhood but by acknowledging guilt and fleeing to the cross of Christ for His forgiveness.

[]{#anchor-dda-statement-14}14. Civil magistrates must use every tool available to end abortion immediately. As murder, abortion is not only a serious sin but a grave crime to be prohibited and punished by the civil government. Although it may take generations to fully eliminate this evil, magistrates must not shirk their responsibility out of cowardice and unfaithfulness. They should remember that they will answer to God.

[]{#anchor-dda-statement-15}15. Civil magistrates must temper their zeal with wisdom from on high. In some cases, wisdom will mean supporting a law that would abolish abortion. In other cases, it may require a ruler to prioritize an incremental strategy offering the most long-term benefits for ending the bloodshed. If the immediate end of abortion is not possible, an incremental approach is not necessarily weak or compromised.[^12]

[]{#anchor-dda-statement-16}16. Christians must prioritize abortion as an electoral issue. While Christian principles on abortion are not inherently partisan, Christians must not let fear of appearing partisan discourage them from voting in a Christian manner. To be sure, the commitments of a particular politician or party may be illusory and cynical, with no desire to end the slaughter. But worse is the party that has made legal abortion its reason to exist. We must both oppose the hypocrisy of the former and abominate the bloodlust of the latter.

[]{#anchor-dda-statement-17}17. Church leaders must regularly and with authority teach against abortion and lead their flocks to love the fruit of the womb. They should also equip their congregants to battle abortion as their station and calling in life allow. In doing so, care should be taken that any division that follows is in fact necessary. Regarding opposition to abortion, good men will differ on method and timing, and comrades in arms will often not see strategy and tactics in the same way. We must grow in our discernment so we can distinguish between reformers and schismatics.

[]{#anchor-dda-statement-18}18. In abhorring abortion, Christians must also be discerning when facing situations that defy easy ethical answers. Sometimes, mothers, fathers, and physicians face difficult decisions where a child may die as a result of otherwise life-saving medical treatment. Survival of the mother and survival of her child may appear mutually exclusive (e.g., in chemotherapy or radiation treatment), and yet here, too, the physician must attend to both patients, disregarding neither. Parents and physician must strive for the survival of both mother and child, desiring to live with a clean conscience before the Lord. Yet while a man plans his way, “the Lord directs his steps” (Prov. 16:9), and if the medical decisions result in the death of the child (or the mother), all parties can take comfort in the knowledge that this was in no way their intent.[^13] They acted wisely, yet God’s decree was that one would live and the other would die. “The Lord giveth, and the Lord taketh away; blessed be the Name of the Lord” (Job 1:21).

[]{#anchor-dda-statement-19}19. Pastors and elders should be especially tender when their sheep suffer the loss of their little ones. The death of a child, born or unborn, is a severe dispensation of the Lord’s providence, and the grieving parents should be the recipients of their shepherds’ and church members’ ongoing guidance and care.

[]{#anchor-dda-statement-20}20. We who are God’s people must love our children—those who are born, and those yet to be born—and we must trust the Lord to provide all that we need, both for us and our children. And not only our own children—we must also love *all* children, those of our covenant communities, but also those of the unbelievers outside it. For our own children have been spared their fate only by God’s mercy. The notion of a surplus population is not of Christ, and let no Christian be guilty of such thoughts toward those who bear the image of God.

[]{#anchor-dda-statement-21}21. We must also uphold and commend the work of adoption for those who are called to it. Rescuing children both inside the womb and outside it has always been a mark of God’s people. The early Christians knew that their identity and communion with Christ was bound up with the little babies left to die, and that to care for them was to honor their Lord Jesus and His birth.

[]{#anchor-dda-statement-22}22. God in His providence will end abortion according to His own counsel—“There are many plans in a man’s heart; nevertheless the counsel of the Lord—that will stand” (Proverbs 19:21). Yet the end of abortion will come only with the gospel, and with the Church leading the world to embrace fruitfulness. Until that day, we labor on, embracing the fruit of the womb, and loving children—and so proving ourselves true sons of our heavenly Father.

[]{#anchor-dda-statement-23}23. In proclaiming these truths, we stand not alone, but in the company of our Lord and of His Church throughout the ages, pronouncing the grave evil and crime of abortion, but also the absolute blessing of children to our families, our churches, and our land. To bring forth children in an evil day, and to call all men to love what God has lavishly bestowed, is to hope for a day we cannot see, and with patience to wait for it. And so it is in this hope that we persevere—in unity with Apostles and Prophets, the holy Fathers of old, the Magisterial Reformers, and the faithful churchmen of all the ages, until, finally, our eyes may see the day when this mighty scourge of evil shall speedily pass away.

In the name of the Father, the Son, and the Holy Spirit, Amen.

[^1]: In saying this we do not condemn all use of contraception. Although most contraception today is not morally justified, occasions do arise where it may be warranted. In such cases, great care must be taken to ensure that whatever method is used does not end a newly conceived life in the womb (see [Statement 6](#anchor-dda-statement-06) for more on this). Such methods (generally barrier) are not, however, the most common methods of contraception used today. Beyond this, the unrestrained use of contraception is symptomatic of the selfishness that despises both a woman’s unique gift of childbearing and the fruit of that gift, children—which leads to the bloodshed we condemn here.

[^2]: That is, “abortion-causing” drugs, whether their operation is direct (e.g., RU-486) or indirect (oral contraceptives such as “The Pill”); see [Statement 6](#anchor-dda-statement-06) below.

[^3]: See [Statement 5](#anchor-dda-statement-05) for explanation of when the taking of human life is justifiable.

[^4]: See [Statement 18](#anchor-dda-statement-18) for discussion of challenging situations which may involve actions that unintentionally result in the death of an unborn child.

[^5]: For a sampling of the unanimity of the Church throughout the ages on this topic, see [“The Witness of Church History”](https://abortion.evangelpresbytery.com/the-witness-of-church-history.html#the-witness-of-church-history) in Evangel Presbytery’s *Abortion and the Church* .

[^6]: The condemnation of the murder of children is ubiquitous across the Old Testament, and these condemnations are pronounced against the Canaanites and the sons of Israel alike. Molech worship required that a child be placed in the mouth of the god as a burnt offering. This is a sin so heinous to God that it is the only evil said never to have entered His mind (Jer. 32:35).

[^7]: Consider the Westminster Larger Catechism: “Q135: What are the duties required in the sixth commandment?” Among the duties required are “all careful studies, and lawful endeavors, to preserve the life of ourselves and others by resisting all thoughts and purposes, subduing all passions, and avoiding all occasions, temptations, and practices, which tend to the unjust taking away the life of any.”

[^8]: This does not mean, of course, that God will grant every man and wife a child. God opens and closes the womb as He sees fit, yet His Creation ordinance still stands for all men across time. See [Statement 10](#anchor-dda-statement-10) for more on a godly approach to infertility.

[^9]: Almost always, it is intrinsic to IVF to produce sixteen embryos to ensure the survival of only one—i.e., a 94% fatality rate. For more, see [“In Vitro Fertilization: Babies in the Fridge”](https://abortion.evangelpresbytery.com/abortions-consequences.html#in-vitro-fertilization-babies-in-the-fridge) in *Abortion and the Church* .

[^10]: See also [“Rape and Incest”](https://abortion.evangelpresbytery.com/dealing-with-common-justifications-for-abortion.html) in *Abortion and the Church* .

[^11]: For discussion of difficult cases involving the life of the mother, see [Statement 18](#anchor-dda-statement-18) in this document. For more on “health of the mother” arguments for abortion, see [“Health of the Mother”](https://abortion.evangelpresbytery.com/dealing-with-common-justifications-for-abortion.html#health-of-the-mother) in *Abortion and the Church* .

[^12]: For an in-depth discussion on these issues, see the entire section [“The Duty of Civil Authorities”](https://abortion.evangelpresbytery.com/the-duty-of-civil-authorities.html#the-duty-of-civil-authorities) in *Abortion and the Church* .

[^13]: Such a case, where medical treatment causes the death of a child in spite of the physician’s best efforts, is the very opposite of abortion. When a mother pays to abort her child it is almost never to save her own life or health, but rather to maintain her lifestyle and future plans.
