## Preface

These **Doctrinal Declarations of the Presbytery** are part of Evangel Presbytery's [constitution](https://bco.evangelpresbytery.com/#c.-constitution-defined). They address matters of such doctrinal and moral weight that we believe they rise above the level of the governmental rules laid down in our [Book of Church Order](https://bco.evangelpresbytery.com/). They are more similar in their nature to the Westminster Standards, aspiring to carry on the work of reform in the church of Jesus Christ by addressing errors and sins particular to our own day and age. Recognizing, however, that these declarations are new and relatively untested, we thought it unwise and presumptuous to append them directly to, or to grant them the same constitutional weight as, the Westminster Standards (see [BCO 28](https://bco.evangelpresbytery.com/02-Form-of-Government.html#amending-the-constitution-of-the-church)). The Doctrinal Declarations of the Presbytery currently include:

1. [Declaration of Doctrine on Sexuality](#sec-declaration-of-doctrine-on-sexuality)

2. [Declaration of Doctrine on Abortion](#sec-declaration-of-doctrine-on-abortion)

For a fuller treatment of matters relating to abortion, see the book *Abortion and the Church* by Evangel Presbytery, available for free online [here](https://abortion.evangelpresbytery.com).
